### ISSUE TITLE
[Q&A]: Making use of shiny

### ISSUE THREAD

**Issue by psychemedia** [coatless-quarto/pyodide#14]
### What's your question?

Hi

This is really handy looking extension. I was wondering whether there's a way of hooking in some of the shinlyite tools, so e.g. you could write a simple app definition in the page and then render the widgets / interactive elements / generated widgets etc from that using the shinylite machinery?

**Comment by coatless** [comment]
So, you want to see the [`{quarto-shinylive}`](https://github.com/quarto-ext/shinylive) extension made by the developers of Shinylive. We won't be able to support the Shinylive case inside of `{quarto-pyodide}` as it requires specific output shims and a scoped iframe. The iframe scoping prevents it from having a shared environment.
