### ISSUE TITLE
[Q&A]: Pyodide for book pages

### ISSUE THREAD

**Issue by m-r-k** [coatless-quarto/pyodide#16]
### What's your question?

If we create a quarto book with nice page navigation and have pyodide blocks on every page, the pyodide engine has to be loaded every time we change (sub)pages. Can this be done more efficiently?

Ideally, pyodide would only have to be loaded when the index.html is opened and all subpages could use it.

**Comment by coatless** [comment]
Unfortunately, each Quarto page is considered a separate instance. If you avoid splitting sections up and keeping chapters on a single long page, the engine will only need to load on one page.
