### ISSUE TITLE
[Q&A]:  Animations

### ISSUE THREAD

**Issue by AustenLamacraft** [coatless-quarto/pyodide#22]
### What's your question?

In the past I've experimented with hooking Pyodide up to p5.js in the past to produce a [visualisation](https://austen.uk/post/online-demos-with-pyodide/) of a Python simulation. This was a bit fiddly, as it involved using a bit Pyodide magic to turn Python objects into JS objects. Does quarto-pyodide allow any easier route to doing this?

**Comment by coatless** [comment]
In short: sort of.

In long: the extension handles the setup and loading done by `assets/ising.js` in your first code block. However, the later portions using JavaScript would need to be dealt with Pyodide's [`js` module](https://pyodide.org/en/stable/usage/type-conversions.html#type-translations-using-js-obj-from-py). 

I probably would say this extension focuses more on simplifying the setup and deployment of Python code with Pyodide.
